new script

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -17,6 +17,15 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y awscli
 
+      - name: Check if Git is installed
+        run: |
+          if ! command -v git &> /dev/null; then
+            echo "Git not found. Installing Git..."
+            sudo apt-get install -y git
+          else
+            echo "Git is already installed."
+          fi
+
       - name: Configure AWS credentials
         run: |
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -58,6 +67,15 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y awscli
+
+      - name: Check if Git is installed
+        run: |
+          if ! command -v git &> /dev/null; then
+            echo "Git not found. Installing Git..."
+            sudo apt-get install -y git
+          else
+            echo "Git is already installed."
+          fi
 
       - name: Configure AWS credentials
         run: |
